package com.myce.notification.entity.type;

public enum MessageTemplateCode {
    EMAIL_VERIFICATION, RESET_PASSWORD, EXPO_REMINDER, EVENT_REMINDER, QR_ISSUED, QR_REISSUED, PAYMENT_COMPLETE,
    EXPO_STATUS_CHANGE, AD_STATUS_CHANGE, RESERVATION_CONFIRM;
}
